import type { Priority, ProjectCategory, ProjectDetail, ProjectHealth, LifecycleStatus, Score, Trend, UrgencyScore } from "../../../packages/contracts/src/index.ts";
import { suggestPriority } from "../../../packages/contracts/src/index.ts";

const today = new Date();
const isoDate = (offset: number) => { const date = new Date(today); date.setDate(date.getDate() + offset); return date.toISOString().slice(0,10); };
const timestamp = (offset: number) => { const date = new Date(today); date.setDate(date.getDate() + offset); return date.toISOString(); };
const projectId = (number:number) => `00000000-0000-4000-8000-${String(number).padStart(12,"0")}`;
const roleId = (projectNumber:number,position:number) => `20000000-${String(projectNumber).padStart(4,"0")}-4000-8000-${String(position).padStart(12,"0")}`;
const seedDepartmentCodes:Record<string,string>={
  "Administracija":"ADM","AML":"AML","Compliance":"COM","Corporate":"COR","Corporate Development":"CDV",
  "Digital i Pravni poslovi":"DPP","Finansije":"FIN","Hotelske operacije":"HOP","Hrana i Piće":"HIP",
  "Investicije":"INV","IT":"IT","IT Bezbednost":"ITB","IT i Analitika":"ITA","Komercijala i IT":"KIT",
  "Kvalitet":"KVA","Ljudski resursi":"LJR","Magacinsko poslovanje":"MAG","Marketing":"MKT",
  "Nabavka":"NAB","Nabavka i Compliance":"NIC","Obračun zarada":"OBZ","Operacije":"OPE",
  "Operacije hrane i pića":"OHP","Pravni poslovi":"PRA","Privatnost":"PRI","Računovodstvo":"RAC",
  "Rizici":"RIZ","Rizici i Bezbednost":"RIB","Tehnika":"TEH","Tehnika i Bezbednost":"TIB",
  "Transport":"TRA","Trezor":"TRZ"
};
export const seedDepartmentCode=(name:string|null)=>name?seedDepartmentCodes[name]??"GEN":"GEN";

type SeedSpec = {
  name:string; category:ProjectCategory; department:string|null; owner:string; sponsor?:string|null; coordinator?:string|null; deliveryLead?:string|null;
  lifecycle:LifecycleStatus; description:string; objective:string; outcome:string; health:ProjectHealth; trend:Trend; progress:number|null;
  baseline?:number|null; forecast?:number|null; mandatory?:number|null; value:Score; urgency:UrgencyScore; consequence:Score; priority?:Priority;
  milestone?:string|null; milestoneIn?:number|null; blocker?:"undefined"|"none"|"blocked"; topBlocker?:string|null;
  decision?:boolean; decisionText?:string|null; decisionIn?:number|null; attention?:boolean; updated:number;
};

const specs:SeedSpec[] = [
  { name:"Atlas",category:"strategic",department:"Corporate",owner:"Portfolio Office",sponsor:"Executive Board",coordinator:"PM Office",deliveryLead:"Operations Lead",lifecycle:"active",
    description:"Program organizacione integracije kojim se objedinjavanju funkcije preuzete kroz akviziciju i istovremeno preispituje postojeći operativni model. Rad obuhvata mapiranje odgovornosti, uklanjanje preklapanja i uspostavljanje jasnog ritma upravljanja bez prekida redovnog poslovanja.",
    objective:"Uspostaviti jednu razumljivu organizacionu logiku, jasne vlasnike procesa i proverljiv način donošenja odluka između centralnih i lokalnih funkcija.",
    outcome:"Odobrena ciljna struktura, potvrđene odgovornosti, dokumentovani procesi i redovno nedeljno i mesečno izveštavanje predato vlasnicima funkcija.",
    health:"amber",trend:"improving",progress:47,baseline:82,forecast:96,value:4,urgency:2,consequence:3,priority:"very_high",milestone:"Evaluacija kontrolisanog test perioda",milestoneIn:12,blocker:"none",decision:true,decisionText:"Potvrditi ciljni organizacioni model i vlasnike tri međufunkcionalna procesa.",decisionIn:9,attention:true,updated:-1 },
  { name:"Horizon",category:"strategic",department:"Investicije",owner:"Development Lead",sponsor:"Investment Committee",coordinator:"Investment PM",deliveryLead:"Technical Development Lead",lifecycle:"planning",
    description:"Višegodišnja investiciona inicijativa za razvoj novog hotelskog kapaciteta, od validacije lokacije i koncepta do finansijske konstrukcije i pripreme dozvola. Projekat mora da spoji tržišni potencijal, standard brenda, tehničku izvodljivost i prihvatljiv povrat na kapital.",
    objective:"Doneti investicionu odluku na osnovu jedinstvenog poslovnog slučaja, realne dinamike dozvola i kontrolisanog raspona troškova.",
    outcome:"Odobren koncept i budžet, zatvorena finansijska konstrukcija, potvrđena lokacija i spreman paket za ulazak u projektovanje i izgradnju.",
    health:"green",trend:"stable",progress:14,baseline:310,forecast:310,value:4,urgency:1,consequence:2,priority:"high",milestone:"Odobrenje koncepta i investicionog raspona",milestoneIn:34,blocker:"none",updated:-3 },
  { name:"Meridian Planning",category:"strategic",department:"Finansije",owner:"Planning Director",sponsor:"Chief Executive",coordinator:"Transformation PM",deliveryLead:"FP&A Lead",lifecycle:"active",
    description:"Redizajn sistema budžetiranja i upravljačkog planiranja kako bi se zamenio godišnji statični ciklus integrisanim modelom plana, rolling forecast-a i scenarija. Inicijativa uključuje jedinstvene pretpostavke, odgovornost poslovnih jedinica i standardizovane upravljačke izveštaje.",
    objective:"Skratiti ciklus planiranja, povećati pouzdanost forecast-a i omogućiti menadžmentu da vidi posledice ključnih poslovnih odluka pre njihovog sprovođenja.",
    outcome:"Jedinstven model budžeta i forecast-a, dogovoreni kalendar, vlasnici pretpostavki i automatizovan paket mesečnih i kvartalnih pregleda.",
    health:"red",trend:"declining",progress:36,baseline:70,forecast:104,value:4,urgency:4,consequence:4,priority:"critical",milestone:"Zaključavanje zajedničkih planskih pretpostavki",milestoneIn:6,blocker:"blocked",topBlocker:"Poslovne jedinice koriste različite definicije prihoda i kapaciteta, pa konsolidovani model još nema stabilnu osnovu.",decision:true,decisionText:"Nametnuti jedinstveni planski rečnik i vlasništvo nad pretpostavkama.",decisionIn:2,attention:true,updated:-2 },
  { name:"Polaris Data",category:"strategic",department:"IT i Analitika",owner:"Data Programme Lead",sponsor:"Executive Board",coordinator:"Data PM",deliveryLead:"Architecture Lead",lifecycle:"blocked",
    description:"Izgradnja zajedničke podatkovne platforme koja treba da poveže operativne, finansijske i komercijalne izvore i ukloni paralelne verzije istine. Obim uključuje vlasništvo nad podacima, arhitekturu integracija, osnovne modele i prioritetne upravljačke slučajeve upotrebe.",
    objective:"Omogućiti pouzdane, pravovremene i međusobno usaglašene podatke za ključne odluke bez ručnog spajanja tabela iz više sistema.",
    outcome:"Produkcijska platforma sa definisanim vlasnicima podataka, kontrolama kvaliteta i prvim setom sertifikovanih upravljačkih dashboarda.",
    health:"critical",trend:"declining",progress:29,baseline:120,forecast:168,value:4,urgency:3,consequence:4,priority:"critical",milestone:"Izbor ciljne integracione arhitekture",milestoneIn:-3,blocker:"blocked",topBlocker:"Nije postignut dogovor o vlasništvu nad ključnim matičnim podacima i prioritetu izvornih sistema.",decision:true,decisionText:"Izabrati arhitektonski pravac i imenovati poslovne data owner-e.",decisionIn:-2,attention:true,updated:-1 },
  { name:"Keystone Governance",category:"strategic",department:"Corporate",owner:"Governance Lead",sponsor:"Supervisory Board",coordinator:"Corporate Secretary",deliveryLead:"Policy Lead",lifecycle:"on_hold",
    description:"Revizija korporativnog upravljačkog modela, matrice ovlašćenja i rada ključnih odbora nakon rasta grupe. Projekat treba da razdvoji strateške, investicione i operativne odluke i smanji broj tema koje nepotrebno završavaju na najvišem nivou.",
    objective:"Uspostaviti brže donošenje odluka uz jasnu odgovornost, kontrolne tačke i dokumentovan trag od predloga do odobrenja.",
    outcome:"Odobrena matrica ovlašćenja, novi mandati odbora, standardizovani decision paper-i i kalendar periodičnih upravljačkih pregleda.",
    health:"amber",trend:"stable",progress:52,baseline:64,forecast:92,value:4,urgency:1,consequence:3,priority:"high",milestone:"Radionica sa članovima ključnih odbora",milestoneIn:18,blocker:"undefined",topBlocker:"Čeka se termin zajedničke radionice sa svim donosiocima odluka.",updated:-11 },
  { name:"Aurora Experience",category:"strategic",department:"Operacije",owner:"Guest Experience Director",sponsor:"Chief Operating Officer",coordinator:"Experience PM",deliveryLead:"Standards Lead",lifecycle:"active",
    description:"Redizajn iskustva gosta kroz ključne tačke kontakta, od rezervacije i dolaska do boravka i post-stay komunikacije. Projekat kombinuje istraživanje gostiju, standarde usluge, digitalne dodirne tačke i promene lokalnih operativnih rutina.",
    objective:"Povećati lojalnost i komercijalnu vrednost gosta kroz doslednije iskustvo koje je prepoznatljivo, merljivo i operativno održivo.",
    outcome:"Usvojen journey model, pilotirani standardi, obučeni lokalni timovi i set KPI-jeva koji povezuje iskustvo gosta sa poslovnim rezultatom.",
    health:"green",trend:"improving",progress:63,baseline:90,forecast:84,value:4,urgency:2,consequence:2,priority:"very_high",milestone:"Završetak pilota na dve lokacije",milestoneIn:15,blocker:"none",updated:-2 },
  { name:"Blue Harbor",category:"strategic",department:"Corporate Development",owner:"Integration Director",sponsor:"Executive Board",coordinator:"Integration PMO",deliveryLead:"Functional Integration Lead",lifecycle:"completed",
    description:"Postakviziciona integracija administrativnih i komercijalnih funkcija sa fokusom na kontinuitet poslovanja, kontrolu troškova i zadržavanje ključnih ljudi. Projekat je vođen kroz odvojene radne tokove sa zajedničkim registrom odluka i zavisnosti.",
    objective:"Ostvariti planirane sinergije bez gubitka poslovnog kontinuiteta i uz transparentno rešavanje organizacionih i sistemskih razlika.",
    outcome:"Kritične funkcije integrisane, sinergije potvrđene, otvorene stavke predane redovnim vlasnicima i formalno zatvoren integracioni program.",
    health:"green",trend:"stable",progress:100,baseline:-24,forecast:-20,value:4,urgency:0,consequence:3,priority:"medium",milestone:"Post-implementation review",milestoneIn:10,blocker:"none",updated:-8 },
  { name:"Summit Energy",category:"strategic",department:"Tehnika",owner:"Energy Programme Lead",sponsor:"Investment Committee",coordinator:"Capital Projects PM",deliveryLead:"Engineering Lead",lifecycle:"active",
    description:"Portfelj investicija u energetsku efikasnost i delimičnu energetsku nezavisnost objekata, uključujući merenje potrošnje, upravljanje opremom i selektivnu proizvodnju energije. Poslovni slučaj zavisi od tehničkog potencijala lokacija i faznog rasporeda kapitala.",
    objective:"Smanjiti trošak i volatilnost energije uz merljivo smanjenje potrošnje i emisija, bez ugrožavanja pouzdanosti objekata.",
    outcome:"Odobren višegodišnji investicioni plan, prioritetne lokacije u realizaciji i operativni sistem za praćenje ušteda u odnosu na baseline.",
    health:"amber",trend:"stable",progress:41,baseline:180,forecast:195,value:4,urgency:2,consequence:3,priority:"very_high",milestone:"Go/No-Go za prvu grupu lokacija",milestoneIn:21,blocker:"none",decision:true,decisionText:"Potvrditi kapitalni limit i redosled lokacija za prvu fazu.",decisionIn:17,attention:true,updated:-5 },
  { name:"Mosaic Brand",category:"strategic",department:"Marketing",owner:"Brand Director",sponsor:"Chief Commercial Officer",coordinator:"Brand PM",deliveryLead:"Creative Operations Lead",lifecycle:"planning",
    description:"Uređenje arhitekture brendova i odnosa između korporativnog, destinacijskog i pojedinačnih hotelskih identiteta. Projekat treba da ukloni nedoslednosti u komunikaciji, olakša komercijalno pozicioniranje i definiše gde je lokalna autonomija opravdana.",
    objective:"Napraviti skalabilan sistem identiteta koji povećava prepoznatljivost i istovremeno čuva relevantne lokalne karakteristike.",
    outcome:"Odobrena brand arhitektura, pravila imenovanja i primene, prioritetni plan tranzicije i upravljački model za buduće izmene.",
    health:"green",trend:"stable",progress:8,baseline:150,forecast:150,value:3,urgency:1,consequence:1,priority:"medium",milestone:"Istraživanje percepcije postojećih brendova",milestoneIn:28,blocker:"undefined",updated:-4 },
  { name:"Citadel Resilience",category:"strategic",department:"Rizici i Bezbednost",owner:"Resilience Lead",sponsor:"Risk Committee",coordinator:"Business Continuity PM",deliveryLead:"Crisis Management Lead",lifecycle:"active",
    description:"Uspostavljanje jedinstvenog okvira otpornosti koji povezuje kontinuitet poslovanja, krizno upravljanje, oporavak sistema i lokalne planove odgovora. Projekat prelazi sa formalnih dokumenata na praktične scenarije, vežbe i merljivu spremnost.",
    objective:"Obezbediti da kritične usluge mogu da nastave rad ili se oporave u prihvatljivom roku tokom realnih operativnih i tehnoloških poremećaja.",
    outcome:"Prioritizovane kritične usluge, potvrđeni planovi oporavka, izvedene vežbe i vlasnici korektivnih akcija sa rokovima.",
    health:"red",trend:"stable",progress:57,baseline:75,forecast:101,value:4,urgency:4,consequence:4,priority:"critical",milestone:"Simulacija prekida centralnih sistema",milestoneIn:8,blocker:"blocked",topBlocker:"Dve poslovne jedinice još nisu potvrdile maksimalno prihvatljiv prekid svojih kritičnih usluga.",decision:false,attention:true,updated:-3 },
  { name:"Orchard Talent",category:"strategic",department:"Ljudski resursi",owner:"People Development Lead",sponsor:"Executive Board",coordinator:"HR Transformation PM",deliveryLead:"Learning Lead",lifecycle:"cancelled",
    description:"Inicijativa za izgradnju interne baze naslednika i strukturisanih razvojnih putanja za ključne rukovodeće pozicije. Prva verzija je obustavljena jer obim nije bio povezan sa potvrđenom organizacionom strukturom i potrebama poslovnih jedinica.",
    objective:"Smanjiti zavisnost od spoljnog zapošljavanja za kritične uloge i učiniti razvoj talenata direktno povezanim sa budućim poslovnim potrebama.",
    outcome:"Obustavljeni koncept arhiviran sa dokumentovanim razlozima; validni nalazi biće preneti u novu inicijativu nakon završetka revizije organizacije.",
    health:"red",trend:"declining",progress:22,baseline:40,forecast:null,value:3,urgency:0,consequence:1,priority:"low",milestone:null,milestoneIn:null,blocker:"none",updated:-34 },
  { name:"Lighthouse Digital",category:"strategic",department:"Komercijala i IT",owner:"Digital Commerce Lead",sponsor:"Chief Commercial Officer",coordinator:"Digital PM",deliveryLead:"Product Lead",lifecycle:"active",
    description:"Transformacija direktnog digitalnog kanala kroz novi booking tok, upravljanje sadržajem, personalizaciju i analitiku konverzije. Projekat koordinira komercijalne prioritete, iskustvo korisnika, integracije sa centralnim sistemima i migraciju sadržaja.",
    objective:"Povećati udeo direktnih rezervacija i smanjiti trošak distribucije uz brži ciklus digitalnih eksperimenata i pouzdanije merenje rezultata.",
    outcome:"Produkcijski kanal sa novim korisničkim tokom, integrisanim merenjem, operativnim content modelom i backlog-om optimizacija u vlasništvu product tima.",
    health:"amber",trend:"improving",progress:71,baseline:45,forecast:51,value:4,urgency:3,consequence:3,priority:"very_high",milestone:"Odluka o produkcijskom puštanju",milestoneIn:7,blocker:"none",decision:true,decisionText:"Potvrditi release obim i prihvatljivi nivo preostalih nekritičnih defekata.",decisionIn:5,attention:true,updated:0 },

  { name:"Sentinel Certification",category:"mandatory",department:"Compliance",owner:"Compliance Lead",sponsor:"Risk Committee",coordinator:"IT Compliance Coordinator",deliveryLead:"Security Lead",lifecycle:"blocked",
    description:"Obavezna sertifikacija kontrolnog okvira za regulisanu delatnost, sa dokazima iz IT-a, operacija i eksternih dobavljača. Rok je fiksiran regulatornim kalendarom, a neispunjenje bi ograničilo nastavak dela poslovnih aktivnosti.",
    objective:"Prikupiti i validirati sve dokaze, zatvoriti utvrđene nedostatke i završiti sertifikaciju pre obaveznog roka.",
    outcome:"Važeći sertifikat, dokumentovan paket dokaza, evidentirane korektivne mere i definisan vlasnik godišnjeg ciklusa obnove.",
    health:"critical",trend:"declining",progress:68,baseline:18,forecast:25,mandatory:18,value:1,urgency:5,consequence:4,priority:"critical",milestone:"Završno eksterno testiranje",milestoneIn:5,blocker:"blocked",topBlocker:"Eksterni partner nije dostavio formalno tehničko odobrenje za poslednju verziju kontrola.",decision:true,decisionText:"Odobriti alternativni put sertifikacije i dodatni eksterni trošak.",decisionIn:-1,attention:true,updated:0 },
  { name:"Gatekeeper AML",category:"mandatory",department:"AML",owner:"AML Officer",sponsor:"Risk Committee",coordinator:"Compliance Analyst",deliveryLead:"Control Testing Lead",lifecycle:"active",
    description:"Periodična procena rizika od pranja novca za digitalne i fizičke kanale sa revizijom metodologije, izvora podataka i procene rezidualnog rizika. Aktivnost je regulatorno obavezna, ali se vodi kao projekat zbog međufunkcionalnog obima i formalne validacije.",
    objective:"Završiti dokumentovanu procenu rizika sa potpunim tragom podataka, obrazloženjima ocena i odobrenjem nadležnih funkcija.",
    outcome:"Usvojena AML procena rizika, potvrđen plan korektivnih aktivnosti i arhiviran regulatorno prihvatljiv paket dokaza.",
    health:"green",trend:"improving",progress:84,baseline:20,forecast:17,mandatory:24,value:1,urgency:4,consequence:4,priority:"very_high",milestone:"Formalno usvajanje procene",milestoneIn:6,blocker:"none",updated:-1 },
  { name:"Privacy Shield DPIA",category:"mandatory",department:"Privatnost",owner:"Data Protection Lead",sponsor:"Legal Director",coordinator:"Privacy Coordinator",deliveryLead:"Product Legal Lead",lifecycle:"active",
    description:"Procena uticaja na privatnost za novu digitalnu uslugu koja obrađuje podatke o korisnicima kroz više sistema i eksternih servisa. Projekat uključuje mapu tokova podataka, pravni osnov, procenu rizika, tehničke mere i formalne konsultacije.",
    objective:"Dokazati da je planirana obrada zakonita, proporcionalna i zaštićena odgovarajućim organizacionim i tehničkim merama pre produkcijskog puštanja.",
    outcome:"Odobrena DPIA, dogovorene preostale mere, ažurirana dokumentacija obrade i kontrola sprovođenja pre go-live datuma.",
    health:"amber",trend:"stable",progress:73,baseline:14,forecast:19,mandatory:21,value:1,urgency:4,consequence:4,priority:"very_high",milestone:"Zatvaranje konsultacija sa poverenikom funkcije",milestoneIn:4,blocker:"undefined",topBlocker:"Čeka se poslednja potvrda tehničkog opisa prenosa podataka eksternom servisu.",updated:-2 },
  { name:"Statutory Consolidation",category:"mandatory",department:"Računovodstvo",owner:"Group Accounting Lead",sponsor:"Finance Director",coordinator:"Reporting Coordinator",deliveryLead:"Consolidation Lead",lifecycle:"completed",
    description:"Usklađivanje konsolidacionog paketa i obaveznih finansijskih obelodanjivanja sa izmenjenim pravilima i strukturom grupe. Projekat je uključio mapiranje konta, validaciju eliminacija i kontrolu uporednih podataka.",
    objective:"Predati potpun, tačan i revizijski proverljiv konsolidovani paket u propisanom roku.",
    outcome:"Izveštaj predat i prihvaćen, revizorske tačke zatvorene, a nova mapiranja i kontrole ugrađeni u redovan ciklus izveštavanja.",
    health:"green",trend:"stable",progress:100,baseline:-12,forecast:-11,mandatory:-10,value:1,urgency:5,consequence:4,priority:"critical",milestone:"Lessons learned i predaja kontrola",milestoneIn:8,blocker:"none",updated:-5 },
  { name:"Privileged Access Review",category:"mandatory",department:"IT Bezbednost",owner:"Information Security Lead",sponsor:"Risk Committee",coordinator:"Security PM",deliveryLead:"Identity Lead",lifecycle:"active",
    description:"Potpuna revizija privilegovanih naloga, administrativnih uloga i načina odobravanja pristupa u kritičnim sistemima. Obim uključuje interne i eksterne korisnike, servisne naloge i dokazivanje periodične kontrole.",
    objective:"Ukloniti nepotrebne privilegije, zatvoriti naloge bez potvrđenog vlasnika i uspostaviti ponovljiv kvartalni proces recertifikacije.",
    outcome:"Potvrđen registar privilegovanih pristupa, dokumentovana odobrenja, sprovedena uklanjanja i automatizovan kontrolni izveštaj.",
    health:"red",trend:"improving",progress:59,baseline:28,forecast:34,mandatory:31,value:2,urgency:4,consequence:4,priority:"critical",milestone:"Eskalacija nepotvrđenih privilegija",milestoneIn:3,blocker:"none",decision:true,decisionText:"Potvrditi automatsko ukidanje pristupa bez odgovora vlasnika nakon isteka roka.",decisionIn:1,attention:true,updated:-1 },
  { name:"Fireline Compliance",category:"mandatory",department:"Tehnika i Bezbednost",owner:"Safety Manager",sponsor:"Operations Director",coordinator:"Facilities Coordinator",deliveryLead:"Technical Compliance Lead",lifecycle:"on_hold",
    description:"Program otklanjanja nalaza protivpožarne kontrole na više lokacija, sa različitim tehničkim rešenjima, lokalnim dozvolama i rokovima izvođača. Iako je regulatorna obaveza jasna, redosled radova mora da minimizira prekide rada objekata.",
    objective:"Zatvoriti sve nalaze visokog rizika pre obaveznih rokova i dokumentovati održiv režim periodičnih provera.",
    outcome:"Potvrde nadležnih organa, izvedeni korektivni radovi, ažurirani planovi evakuacije i vlasnici preventivnog održavanja.",
    health:"red",trend:"stable",progress:44,baseline:39,forecast:67,mandatory:52,value:1,urgency:4,consequence:4,priority:"critical",milestone:"Nastavak radova na kritičnoj lokaciji",milestoneIn:13,blocker:"blocked",topBlocker:"Radovi su privremeno obustavljeni dok se ne potvrdi termin bezbednog zatvaranja dela objekta.",attention:true,updated:-10 },
  { name:"License Matrix",category:"mandatory",department:"Pravni poslovi",owner:"Legal Operations Lead",sponsor:"Legal Director",coordinator:"Legal Analyst",deliveryLead:"Licensing Specialist",lifecycle:"planning",
    description:"Centralizacija svih poslovnih dozvola, licenci, sertifikata i rokova obnove koji su trenutno raspoređeni po funkcijama i lokacijama. Projekat mora da razjasni odgovornost, dokumentaciju i zavisnosti između lokalnih i centralnih obaveza.",
    objective:"Napraviti jedinstven i pouzdan registar obaveznih dozvola sa vlasnicima, rokovima i dokazima o blagovremenoj obnovi.",
    outcome:"Operativan registar sa upozorenjima, potvrđenim vlasnicima i standardnim mesečnim pregledom obaveza koje ulaze u kritični period.",
    health:"green",trend:"stable",progress:5,baseline:100,forecast:100,mandatory:120,value:1,urgency:1,consequence:3,priority:"medium",milestone:"Potvrda taksonomije dozvola",milestoneIn:20,blocker:"undefined",updated:-6 },
  { name:"Payroll Directive",category:"mandatory",department:"Obračun zarada",owner:"Payroll Manager",sponsor:"Finance Director",coordinator:"HRIS Coordinator",deliveryLead:"Payroll Systems Lead",lifecycle:"active",
    description:"Prilagođavanje obračuna zarada novim poreskim i izveštajnim pravilima sa promenama u sistemu, kontrolama i zaposleničkoj dokumentaciji. Fiksni datum primene ne ostavlja prostor za pomeranje, pa paralelno teku konfiguracija, test i komunikacija.",
    objective:"Obezbediti tačan prvi obračun po novim pravilima i potpunu usklađenost prijava bez ručnih korekcija velikog obima.",
    outcome:"Produkcijska konfiguracija, potpisani test scenariji, ažurirane procedure i završen prvi kontrolisani obračun.",
    health:"amber",trend:"declining",progress:66,baseline:12,forecast:16,mandatory:14,value:1,urgency:5,consequence:4,priority:"critical",milestone:"Paralelni obračun i poređenje rezultata",milestoneIn:2,blocker:"none",decision:true,decisionText:"Odobriti dodatni vikend rad za zatvaranje test ciklusa.",decisionIn:0,attention:true,updated:0 },
  { name:"Archive Retention",category:"mandatory",department:"Administracija",owner:"Records Manager",sponsor:"Legal Director",coordinator:"Document Coordinator",deliveryLead:"Archive Vendor Lead",lifecycle:"active",
    description:"Usklađivanje fizičke i elektronske dokumentacije sa rokovima čuvanja, pravilima uništenja i ograničenjima pristupa. Projekat uključuje klasifikaciju velikog nasleđenog fonda i uspostavljanje pravila za novonastalu dokumentaciju.",
    objective:"Smanjiti pravni i operativni rizik kroz doslednu klasifikaciju, kontrolisano čuvanje i dokazivo uništenje po isteku roka.",
    outcome:"Usvojen retention schedule, klasifikovan prioritetni fond, dokumentovan postupak uništenja i redovan godišnji pregled izuzetaka.",
    health:"green",trend:"improving",progress:49,baseline:130,forecast:124,mandatory:150,value:0,urgency:2,consequence:3,priority:"medium",milestone:"Odobrenje pravila za elektronsku arhivu",milestoneIn:17,blocker:"none",updated:-4 },
  { name:"Vendor Screening",category:"mandatory",department:"Nabavka i Compliance",owner:"Third-Party Risk Lead",sponsor:"Risk Committee",coordinator:"Procurement Analyst",deliveryLead:"Screening Operations Lead",lifecycle:"active",
    description:"Uvođenje obavezne provere dobavljača prema sankcijama, vlasničkoj strukturi i reputacionim kriterijumima pre ugovaranja i tokom trajanja odnosa. Projekat povezuje nabavku, pravne poslove, compliance i vlasnike ugovora.",
    objective:"Sprečiti angažovanje neprihvatljivih trećih strana i obezbediti dosledan, dokumentovan trag od provere do odluke.",
    outcome:"Jedinstven screening proces, pragovi eskalacije, integrisana evidencija i periodično ponovno proveravanje aktivnih dobavljača.",
    health:"amber",trend:"stable",progress:32,baseline:75,forecast:83,mandatory:90,value:1,urgency:3,consequence:4,priority:"very_high",milestone:"Pilot na novim dobavljačima visokog rizika",milestoneIn:11,blocker:"undefined",updated:-8 },
  { name:"Incident Register",category:"mandatory",department:"Rizici",owner:"Operational Risk Lead",sponsor:"Risk Committee",coordinator:"Risk Analyst",deliveryLead:"Control Assurance Lead",lifecycle:"completed",
    description:"Standardizacija prijave, klasifikacije i praćenja operativnih incidenata radi ispunjavanja internih i regulatornih obaveza. Prethodni proces je zavisio od lokalnih tabela i neujednačenih pragova materijalnosti.",
    objective:"Obezbediti potpunu i pravovremenu evidenciju incidenata sa jasnim vlasništvom, analizom uzroka i praćenjem korektivnih mera.",
    outcome:"Centralni registar u upotrebi, usaglašena taksonomija, obučeni korisnici i mesečni kontrolni pregled kvaliteta podataka.",
    health:"green",trend:"improving",progress:100,baseline:-18,forecast:-16,mandatory:-12,value:1,urgency:2,consequence:4,priority:"high",milestone:"Prvi mesečni quality review",milestoneIn:13,blocker:"none",updated:-6 },
  { name:"Accessibility Standard",category:"mandatory",department:"Digital i Pravni poslovi",owner:"Digital Compliance Lead",sponsor:"Legal Director",coordinator:"Accessibility Coordinator",deliveryLead:"Frontend Lead",lifecycle:"planning",
    description:"Usklađivanje javnih digitalnih servisa sa zahtevima pristupačnosti, uključujući dizajn, sadržaj, navigaciju tastaturom i kompatibilnost sa asistivnim tehnologijama. Projekat počinje inventarom i procenom najvećih rizika po kanalima.",
    objective:"Dostići definisani standard pristupačnosti u prioritetnim korisničkim tokovima i ugraditi kontrole u budući razvoj.",
    outcome:"Potvrđen remediation plan, zatvoreni kritični nalazi, nezavisna provera i operativna check-lista za nove objave.",
    health:"green",trend:"stable",progress:null,baseline:210,forecast:210,mandatory:240,value:1,urgency:0,consequence:2,priority:"low",milestone:"Završetak početnog audita",milestoneIn:31,blocker:"undefined",updated:-12 },
  { name:"Food Safety Renewal",category:"mandatory",department:"Operacije hrane i pića",owner:"Food Safety Manager",sponsor:"Operations Director",coordinator:"Quality Coordinator",deliveryLead:"Site Operations Lead",lifecycle:"cancelled",
    description:"Prvobitno otvoren projekat za obnovu sertifikacije bez provere da li je obim već pokriven postojećim redovnim procesom. Nakon revizije utvrđeno je da aktivnosti pripadaju godišnjem ciklusu funkcije i ne zahtevaju posebnu projektnu organizaciju.",
    objective:"Potvrditi obaveze obnove i obezbediti da ni jedna lokacija ne izgubi važeći status.",
    outcome:"Pogrešno otvoren projekat je zatvoren, a sve validne aktivnosti i rokovi preneti su u operativni registar vlasničke funkcije.",
    health:"green",trend:"stable",progress:0,baseline:45,forecast:null,mandatory:50,value:0,urgency:1,consequence:3,priority:"low",milestone:null,milestoneIn:null,blocker:"none",updated:-21 },

  { name:"Ledger Flow",category:"operational_improvement",department:"Finansije",owner:"Finance Process Lead",sponsor:"Finance Director",coordinator:"Process Coordinator",deliveryLead:"Record-to-Report Lead",lifecycle:"active",
    description:"Redizajn toka finansijskih podataka i mesečnog zatvaranja sa ciljem da se uklone višestruka ručna usaglašavanja i kasne korekcije. Projekat mapira ulaze po funkcijama, standardizuje kontrolne tačke i uvodi vidljiv dnevni plan zatvaranja.",
    objective:"Skratiti mesečno zatvaranje, smanjiti broj naknadnih knjiženja i učiniti uzroke kašnjenja vidljivim pre kraja ciklusa.",
    outcome:"Standardizovan close calendar, automatizovane ključne kontrole, dashboard otvorenih stavki i potvrđena odgovornost po svakom koraku.",
    health:"green",trend:"improving",progress:61,baseline:55,forecast:48,value:3,urgency:2,consequence:2,priority:"high",milestone:"Pilot novog mesečnog zatvaranja",milestoneIn:16,blocker:"none",updated:-2 },
  { name:"Northstar Procurement",category:"operational_improvement",department:"Nabavka",owner:"Procurement Lead",sponsor:"Operations Director",coordinator:"Process Analyst",deliveryLead:"Category Management Lead",lifecycle:"active",
    description:"Standardizacija specifikacija, zahteva i toka odobravanja nabavki koji se trenutno razlikuju po lokacijama i kategorijama. Projekat uvodi jasne pragove, kvalitetnije ulazne zahteve i transparentno vreme zadržavanja u svakoj tački procesa.",
    objective:"Smanjiti ciklus nabavke i broj vraćenih zahteva bez gubitka kontrole troška, konkurentnosti i razdvajanja dužnosti.",
    outcome:"Jedinstven intake obrazac, odobreni tokovi po pragovima, dashboard ciklusa i vlasnici kategorija sa jasnim servisnim nivoima.",
    health:"amber",trend:"stable",progress:38,baseline:70,forecast:77,value:2,urgency:2,consequence:2,priority:"medium",milestone:"Finalni predlog toka od zahteva do ugovora",milestoneIn:24,blocker:"undefined",updated:-9 },
  { name:"Warehouse Pulse",category:"operational_improvement",department:"Magacinsko poslovanje",owner:"Warehouse Operations Lead",sponsor:"Operations Director",coordinator:"Inventory Analyst",deliveryLead:"Warehouse Systems Lead",lifecycle:"active",
    description:"Uvođenje pouzdanog pregleda stanja, obrta i kritičnih odstupanja zaliha u centralnim i lokalnim magacinima. Projekat povezuje standarde prijema, šifarnik artikala, ciklične popise i odgovornost za rešavanje razlika.",
    objective:"Smanjiti neobjašnjive razlike, nestašice i prekomerne zalihe kroz ranije signale i doslednu obradu odstupanja.",
    outcome:"Dnevni operativni pregled zaliha, potvrđeni pragovi upozorenja, ciklični popis i merljivo smanjenje starih otvorenih razlika.",
    health:"red",trend:"declining",progress:43,baseline:50,forecast:79,value:3,urgency:3,consequence:3,priority:"very_high",milestone:"Stabilizacija šifarnika prioritetnih artikala",milestoneIn:9,blocker:"blocked",topBlocker:"Tri lokacije i dalje koriste lokalne duplikate artikala koji se ne mogu pouzdano konsolidovati.",decision:true,decisionText:"Odobriti privremeno centralno upravljanje matičnim podacima do završetka čišćenja.",decisionIn:4,attention:true,updated:-3 },
  { name:"Service Desk Reset",category:"operational_improvement",department:"IT",owner:"IT Service Manager",sponsor:"Chief Information Officer",coordinator:"Service Improvement Lead",deliveryLead:"Support Operations Lead",lifecycle:"active",
    description:"Redizajn rada servis deska sa fokusom na klasifikaciju zahteva, vlasništvo, prioritizaciju i rešavanje ponavljajućih uzroka. Postojeći model meri broj zatvorenih tiketa, ali ne razlikuje stvarno rešavanje problema od administrativnog zatvaranja.",
    objective:"Povećati brzinu i kvalitet podrške, smanjiti ponovljene incidente i dati poslovnim funkcijama razumljiv pregled usluge.",
    outcome:"Nova taksonomija, jasni nivoi eskalacije, knowledge base, problem-management ritam i KPI-jevi zasnovani na ishodu za korisnika.",
    health:"green",trend:"improving",progress:76,baseline:44,forecast:42,value:3,urgency:3,consequence:2,priority:"high",milestone:"Puštanje novog modela prioritizacije",milestoneIn:6,blocker:"none",updated:-1 },
  { name:"Spare Parts Control",category:"operational_improvement",department:"Tehnika",owner:"Maintenance Planning Lead",sponsor:"Technical Director",coordinator:"Technical Buyer",deliveryLead:"Maintenance Systems Lead",lifecycle:"planning",
    description:"Uređenje planiranja i dostupnosti rezervnih delova za kritičnu opremu kako bi se smanjili prekidi i hitne nabavke. Projekat povezuje kritičnost opreme, istoriju kvarova, minimalne zalihe i standarde skladištenja.",
    objective:"Obezbediti raspoloživost kritičnih delova uz kontrolisan kapital vezan u zalihama i manje neplaniranih hitnih nabavki.",
    outcome:"Klasifikovana oprema, definisane min/max zalihe, uređeni šifarnici i pregled delova sa rizikom od nestašice ili zastarelosti.",
    health:"green",trend:"stable",progress:null,baseline:120,forecast:120,value:2,urgency:1,consequence:3,priority:"medium",milestone:"Potvrda liste kritične opreme",milestoneIn:25,blocker:"undefined",updated:-7 },
  { name:"Shift Planner",category:"operational_improvement",department:"Operacije",owner:"Workforce Planning Lead",sponsor:"Operations Director",coordinator:"HR Operations Analyst",deliveryLead:"Scheduling Product Lead",lifecycle:"active",
    description:"Standardizacija planiranja smena u okruženju sa sezonskim oscilacijama, različitim lokalnim pravilima i čestim ručnim izmenama. Projekat treba da poveže forecast obima, potrebne kompetencije, dostupnost ljudi i ograničenja radnog vremena.",
    objective:"Smanjiti prekovremeni rad i poslednje izmene rasporeda uz bolje pokrivanje stvarne operativne potrebe.",
    outcome:"Pilotirani standard planiranja, jasna pravila, transparentan pregled odstupanja i potvrđen pristup za širenje na ostale lokacije.",
    health:"amber",trend:"improving",progress:54,baseline:66,forecast:72,value:3,urgency:3,consequence:2,priority:"high",milestone:"Uporedna analiza plana i stvarne potrebe",milestoneIn:14,blocker:"none",updated:-4 },
  { name:"Invoice Match",category:"operational_improvement",department:"Računovodstvo",owner:"Accounts Payable Lead",sponsor:"Finance Director",coordinator:"Process Automation Analyst",deliveryLead:"ERP Functional Lead",lifecycle:"blocked",
    description:"Automatizacija uparivanja faktura, narudžbenica i prijema robe radi smanjenja ručne obrade i kašnjenja plaćanja. Kvalitet automatizacije direktno zavisi od discipline u ranijim koracima nabavke i prijema.",
    objective:"Povećati procenat faktura koje prolaze bez ručne intervencije i skratiti vreme rešavanja izuzetaka.",
    outcome:"Pravila automatskog uparivanja, standardni redovi za izuzetke, vlasnici uzroka i merljiv rast straight-through obrade.",
    health:"critical",trend:"declining",progress:35,baseline:38,forecast:76,value:3,urgency:4,consequence:3,priority:"critical",milestone:"Odluka o obaveznom korišćenju narudžbenica",milestoneIn:3,blocker:"blocked",topBlocker:"Veliki deo faktura stiže bez validne narudžbenice ili potvrđenog prijema, pa tehnička automatizacija nema pouzdan ulaz.",decision:true,decisionText:"Uvesti pravilo bez narudžbenice nema obrade, sa jasno definisanim izuzecima.",decisionIn:1,attention:true,updated:0 },
  { name:"Contract Intake",category:"operational_improvement",department:"Pravni poslovi",owner:"Legal Operations Lead",sponsor:"Legal Director",coordinator:"Contract Analyst",deliveryLead:"Workflow Lead",lifecycle:"active",
    description:"Uvođenje jedinstvenog ulaza za zahteve za ugovore, prioritetizaciju i transparentno praćenje pregleda. Trenutni zahtevi dolaze različitim kanalima, često bez ključnih poslovnih informacija i realnog roka.",
    objective:"Smanjiti vreme od zahteva do spremnog ugovora i omogućiti da pravni kapacitet bude usmeren prema vrednosti i riziku.",
    outcome:"Standardni intake, pravila prioriteta, vidljiv backlog i servisni nivoi po tipu ugovora sa jasnim statusom za naručioca.",
    health:"green",trend:"improving",progress:69,baseline:49,forecast:45,value:2,urgency:2,consequence:2,priority:"medium",milestone:"Pilot sa nabavkom i komercijalom",milestoneIn:5,blocker:"none",updated:-2 },
  { name:"Fleet Maintenance",category:"operational_improvement",department:"Transport",owner:"Fleet Manager",sponsor:"Operations Director",coordinator:"Maintenance Coordinator",deliveryLead:"Fleet Systems Lead",lifecycle:"on_hold",
    description:"Standardizacija preventivnog održavanja voznog parka i praćenja ukupnog troška po vozilu. Projekat treba da objedini termine servisa, kvarove, rezervna vozila, ugovore i kriterijume zamene.",
    objective:"Smanjiti neplanirane kvarove i trošak hitnih popravki uz bolju odluku o održavanju, zameni ili povlačenju vozila.",
    outcome:"Jedinstven plan održavanja, kompletna istorija troška, upozorenja za obavezne radove i kriterijumi za godišnji plan zamene.",
    health:"amber",trend:"stable",progress:48,baseline:58,forecast:90,value:2,urgency:1,consequence:2,priority:"medium",milestone:"Nastavak pilota nakon obnove ugovora",milestoneIn:22,blocker:"undefined",topBlocker:"Pilot je privremeno zaustavljen do potvrde novog okvira saradnje sa servisnom mrežom.",updated:-13 },
  { name:"Recruitment Handoff",category:"operational_improvement",department:"Ljudski resursi",owner:"Talent Acquisition Lead",sponsor:"HR Director",coordinator:"HR Process Analyst",deliveryLead:"HR Operations Lead",lifecycle:"completed",
    description:"Redizajn prelaza od odobrenog zapošljavanja do prvog radnog dana, sa jasnim odgovornostima regrutacije, HR administracije, IT-a i linijskog menadžera. Prethodni proces je stvarao praznine u dokumentaciji, opremi i komunikaciji kandidatu.",
    objective:"Obezbediti predvidiv i potpun onboarding početak bez hitnih intervencija poslednjeg dana.",
    outcome:"Jedinstvena check-lista, automatizovane notifikacije, potvrđeni rokovi funkcija i kontrolni pregled svih novih zaposlenih pre datuma početka.",
    health:"green",trend:"improving",progress:100,baseline:-30,forecast:-27,value:2,urgency:0,consequence:2,priority:"low",milestone:"Merenje rezultata posle tri meseca",milestoneIn:38,blocker:"none",updated:-14 },
  { name:"Menu Engineering",category:"operational_improvement",department:"Hrana i Piće",owner:"F&B Performance Lead",sponsor:"Commercial Director",coordinator:"Menu Analyst",deliveryLead:"Culinary Operations Lead",lifecycle:"active",
    description:"Uvođenje analitičkog pristupa strukturi menija, cenama, marži i operativnoj složenosti pripreme. Projekat kombinuje prodajne podatke, standardne normative, pozicioniranje ponude i testiranje promena na odabranim lokacijama.",
    objective:"Povećati kontribucionu maržu i jednostavnost operacije bez narušavanja identiteta ponude i zadovoljstva gosta.",
    outcome:"Redizajniran pilot meni, potvrđene cene i normativi, jasni kriterijumi za širenje i redovan kvartalni pregled performansi artikala.",
    health:"green",trend:"improving",progress:58,baseline:60,forecast:57,value:3,urgency:2,consequence:1,priority:"high",milestone:"Završetak A/B pilota ponude",milestoneIn:10,blocker:"none",updated:-3 },
  { name:"Training Calendar",category:"operational_improvement",department:"Ljudski resursi",owner:"Learning Operations Lead",sponsor:"HR Director",coordinator:"Learning Coordinator",deliveryLead:"HR Systems Analyst",lifecycle:"cancelled",
    description:"Pokušaj da se objedine sve lokalne obuke u centralni projekat bez jasnog transformacionog ishoda i bez potrebe za posebnom projektnom organizacijom. Analiza je pokazala da većina aktivnosti pripada redovnom planiranju i administraciji learning funkcije.",
    objective:"Povećati vidljivost obuka, rokova i obaveznih potvrda na nivou cele organizacije.",
    outcome:"Projekat zatvoren, a korisni zahtevi preneti u unapređenje redovnog learning kalendara i operativnog izveštavanja funkcije.",
    health:"green",trend:"stable",progress:12,baseline:80,forecast:null,value:0,urgency:0,consequence:0,priority:"low",milestone:null,milestoneIn:null,blocker:"none",updated:-28 },
  { name:"Cash Forecasting",category:"operational_improvement",department:"Trezor",owner:"Treasury Lead",sponsor:"Finance Director",coordinator:"FP&A Analyst",deliveryLead:"Cash Management Lead",lifecycle:"active",
    description:"Unapređenje kratkoročnog forecast-a gotovine kroz standardne ulaze od prodaje, nabavke, investicija i finansiranja. Trenutni pregled kasno reaguje na promene i ne razlikuje pouzdane obaveze od procena niske sigurnosti.",
    objective:"Povećati tačnost 13-nedeljnog cash forecast-a i omogućiti ranije upravljanje likvidnošću i finansiranjem.",
    outcome:"Jedinstven nedeljni model, kategorije pouzdanosti, vlasnici ulaza i analiza odstupanja koja sistematski poboljšava naredne prognoze.",
    health:"amber",trend:"improving",progress:46,baseline:52,forecast:56,value:3,urgency:4,consequence:3,priority:"very_high",milestone:"Prvi kompletan 13-nedeljni ciklus",milestoneIn:9,blocker:"none",updated:-1 },
  { name:"Quality Walkthrough",category:"operational_improvement",department:"Kvalitet",owner:"Quality Assurance Lead",sponsor:"Operations Director",coordinator:"Quality Analyst",deliveryLead:"Site Excellence Lead",lifecycle:"planning",
    description:"Standardizacija operativnih obilazaka i praćenja korektivnih mera na lokacijama. Cilj nije još jedna check-lista, već povezivanje nalaza sa odgovornom osobom, rokom, ponavljanjem i dokazom zatvaranja.",
    objective:"Povećati brzinu zatvaranja važnih nalaza i prepoznati sistemske probleme koji se ponavljaju na više lokacija.",
    outcome:"Jedinstven standard obilaska, prioriteti nalaza, digitalni registar akcija i mesečni pregled ponovljenih uzroka.",
    health:"green",trend:"stable",progress:3,baseline:95,forecast:95,value:2,urgency:1,consequence:2,priority:"low",milestone:"Potvrda pilot check-liste",milestoneIn:19,blocker:"undefined",updated:-5 },
  { name:"Room Readiness",category:"operational_improvement",department:"Hotelske operacije",owner:"Rooms Division Lead",sponsor:"Operations Director",coordinator:"Operations Analyst",deliveryLead:"Housekeeping Excellence Lead",lifecycle:"active",
    description:"Smanjenje kašnjenja u spremnosti soba kroz bolju koordinaciju housekeeping-a, recepcije, tehnike i prioriteta dolazaka. Projekat analizira stvarno vreme prolaska, razloge ponovnog rada i način ranog signaliziranja rizika.",
    objective:"Povećati procenat soba spremnih u obećano vreme i smanjiti broj ručnih eskalacija na dan dolaska.",
    outcome:"Zajednički operativni pregled, standard prioritizacije, vlasnici glavnih uzroka i merljivo stabilniji rezultat tokom vršnog opterećenja.",
    health:"amber",trend:"stable",progress:51,baseline:35,forecast:41,value:3,urgency:3,consequence:2,priority:"high",milestone:"Test prediktivnog upozorenja za kašnjenje",milestoneIn:4,blocker:"none",updated:-2 },
  { name:"Master Data Cleanup",category:"operational_improvement",department:null,owner:"Master Data Coordinator",sponsor:"Finance Director",coordinator:null,deliveryLead:"ERP Data Lead",lifecycle:"blocked",
    description:"Čišćenje duplikata i nedoslednih atributa u ključnim šifarnicima dobavljača, artikala, kupaca i organizacionih jedinica. Projekat je otvoren bez potvrđenog vodećeg departmenta, što namerno testira slučaj podeljenog ili nejasnog vlasništva.",
    objective:"Uspostaviti pouzdane matične podatke i sprečiti ponovno nastajanje duplikata kroz jasna pravila kreiranja i odobravanja.",
    outcome:"Očišćen prioritetni skup, definisan data ownership, kontrole duplikata i redovan izveštaj o kvalitetu matičnih podataka.",
    health:"red",trend:"declining",progress:27,baseline:62,forecast:110,value:3,urgency:2,consequence:3,priority:"high",milestone:"Imenovanje poslovnih vlasnika šifarnika",milestoneIn:2,blocker:"blocked",topBlocker:"Ni jedna funkcija trenutno ne prihvata konačnu odgovornost za zajedničke šifarnike.",decision:true,decisionText:"Imenovati vodeći department i data owner-e po domenu.",decisionIn:-4,attention:true,updated:-9 }
];

export const seedProjects:ProjectDetail[] = specs.map((spec,index) => {
  const number=index+1; const suggested=suggestPriority(spec.value,spec.urgency,spec.consequence);
  const roles=[
    ...(spec.sponsor?[{name:spec.sponsor,role:"sponsor" as const}]:[]),
    {name:spec.owner,role:"owner" as const},
    ...(spec.coordinator?[{name:spec.coordinator,role:"coordinator" as const}]:[]),
    ...(spec.deliveryLead?[{name:spec.deliveryLead,role:"executor" as const}]:[])
  ].map((assignment,roleIndex)=>({...assignment,id:roleId(number,roleIndex+1),isPrimary:true,position:0}));
  const project:ProjectDetail = {
    id:projectId(number),projectCode:`${today.getUTCFullYear()}-${seedDepartmentCode(spec.department)}-${String(number).padStart(3,"0")}`,projectNumber:number,name:spec.name,category:spec.category,leadDepartment:spec.department,leadDepartmentId:null,roles,lifecycleStatus:spec.lifecycle,
    description:spec.description,objective:spec.objective,outcome:spec.outcome,health:spec.health,trend:spec.trend,progress:spec.progress,
    plannedStart:isoDate(-120+(number%20)),actualStart:spec.lifecycle==="planning"?null:isoDate(-114+(number%20)),
    baselineFinish:spec.baseline===undefined||spec.baseline===null?null:isoDate(spec.baseline),forecastFinish:spec.forecast===undefined||spec.forecast===null?null:isoDate(spec.forecast),
    mandatoryDeadline:spec.mandatory===undefined||spec.mandatory===null?null:isoDate(spec.mandatory),valueScore:spec.value,urgencyScore:spec.urgency,consequenceScore:spec.consequence,
    finalPriority:spec.priority??suggested,suggestedPriority:suggested,nextMilestone:spec.milestone??null,nextMilestoneDate:spec.milestoneIn===undefined||spec.milestoneIn===null?null:isoDate(spec.milestoneIn),
    blockerState:spec.blocker==="blocked"?"blocked":"none",topBlocker:spec.topBlocker??null,decisionRequired:spec.decision??false,decisionText:spec.decisionText??null,
    decisionDueDate:spec.decisionIn===undefined||spec.decisionIn===null?null:isoDate(spec.decisionIn),managementAttention:spec.attention??false,isDemo:true,lastUpdatedAt:timestamp(spec.updated),lastStatusAt:timestamp(spec.updated)
  };
  return project;
});

export const seedStats = {
  projects:seedProjects.length,
  strategic:seedProjects.filter(p=>p.category==="strategic").length,
  mandatory:seedProjects.filter(p=>p.category==="mandatory").length,
  operational:seedProjects.filter(p=>p.category==="operational_improvement").length
};
